apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus-deployment
spec:
  selector:
    matchLabels:
      app: nginx-plus
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-plus
    spec:
      containers:
      - name: mynginxplus
        image: docker.io/library/mr-nplus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

