apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus-deployment
spec:
  selector:
    matchLabels:
      app: nginx-plus
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-plus
    spec:
      containers:
        - name: mynginxplus
          image: docker.io/library/mr-nplus:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
